### 配置网关反向代理
zuul:
  routes:
    api-a:
      ### 以 /api-member/访问转发到会员服务
      path: /member/**
      serviceId: app-jc-member
    api-b:
      ### 以 /api-order/访问转发到订单服务
      path: /order/**
      serviceId: app-jc-order
    api-c:
      ### 以 /api-order/访问转发到订单服务
      path: /pay/**
      serviceId: app-jc-pay
